### ISSUE TITLE
Suggestion: Changing apearance per level?

### ISSUE THREAD

**Issue by Sketaful** [blaxxun-boop/Backpacks#50]
You already support removing or showing different parts to make the backpacks look different. I would love ifyou could add the possibility to change the apperance for each level as well. This would make it possible to make backpacks that you see a difference on when leveling up. 

Maybe already possible? If so, how?

**Comment by IanMunster** [comment]
I've tried a few upgrades with this backpack, posted below.
Sadly it does not work and the console prints out the error also posted below.
Cheers!
**Backpacks.yml**
```yml
"Workbench Backpack":
 description: "This Backpack is useful for crafting new outposts! Workbench, portal and more, all conveniently stored and ready!"
 size: 3x2
 unique: type
 appearance:
  BackpackBody: visible
  BackpackFlap: visible
  Sleepbag: visible
  BackpackStrapTop: visible
  BackpackStrapBottom: visible
  Knife: hidden
  Knifesheath: hidden
  Pickaxe: hidden
  ToolstrapTop: hidden
  ToolstrapBottom: hidden
  Pot: visible
  Teapot: visible
  RingBottomLeft: visible
  PouchFront: hidden
  PouchLeft: hidden
  MetalclipLeft: hidden
  MetalclipFrontLeft: visible
  MetalclipFrontRight: visible
 weight factor: 0.5
 teleport: false
 valid items:
  - Wood
  - FineWood
  - GreydwarfEye
  - SurtlingCore
  - Stone
  - Coal
  - Copper
  - Iron
 crafting:
  station: Workbench
  level: 2
  costs:
   BronzeNails: 5
   DeerHide: 10
   LeatherScraps: 10
 upgrade:
  1:
   Iron: 5
   ElderBark: 10
   Guck: 2
   size: 4x2 
   appearance:
    Pickaxe: visible
    ToolstrapBottom: visible 
    PouchFront: visible
   valid items:
    - Copper 
   teleport: true 
  2:
   Silver: 5
   WolfPelt: 3
   JuteRed: 2 
   size: 3x3 
   appearance:
    Knife: visible
    Knifesheath: visible
    ToolstrapTop: visible
    PouchLeft: visible
    MetalclipLeft: visible
   valid items:
    - Iron
  3:
   BlackMetal: 5
   LinenThread: 10
   LoxPelt: 2
   size: 4x3
```
**BepInEx Log**
```log
[Error  : Unity Log] Found Backpacks config errors in file at D:\games\steam\steamapps\common\Valheim\BepInEx\config\Backpacks.yml. Please review the syntax of your file:
Expecting a number while parsing the costs for 'appearance'. Got unexpected System.Collections.Generic.Dictionary`2[System.Object,System.Object] in upgrade level 1 in backpack definition for backpack 'Workbench Backpack'.
Expecting a number while parsing the costs for 'valid items'. Got unexpected System.Collections.Generic.List`1[System.Object] in upgrade level 1 in backpack definition for backpack 'Workbench Backpack'.
The amount of teleport must be a valid number. Got unexpected true in backpack definition for backpack 'Workbench Backpack'. in upgrade level 1 in backpack definition for backpack 'Workbench Backpack'.
Expecting a number while parsing the costs for 'appearance'. Got unexpected System.Collections.Generic.Dictionary`2[System.Object,System.Object] in upgrade level 2 in backpack definition for backpack 'Workbench Backpack'.
Expecting a number while parsing the costs for 'valid items'. Got unexpected System.Collections.Generic.List`1[System.Object] in upgrade level 2 in backpack definition for backpack 'Workbench Backpack'.
```
